master:
  stage: deploy
  only:
    - master
  tags:
    - nsur-runner-1
  script:
    - cd /home/gitlab-runner/publicwebsite/frontend
    - git fetch origin master
    - git reset --hard origin/master
#    - git clean -f -d
    - git pull
    - npm i --force
    - npm run build
    - cd /home/gitlab-runner/publicwebsite/backend
    - npm i
    - npm run build
    - pm2 delete "premierx-backend" || exit_code=$?
    - pm2 start premieRx.pm2.config.js --env production
    - mkdir -p /home/gitlab-runner/publicwebsite/backend/dist/uploads/contract/
    - mkdir -p /home/gitlab-runner/publicwebsite/backend/dist/uploads/nda/
    - mkdir -p /home/gitlab-runner/publicwebsite/backend/dist/uploads/marketingMaterials/
    - mkdir -p /home/gitlab-runner/publicwebsite/backend/dist/uploads/temp/
    - mkdir -p /home/gitlab-runner/publicwebsite/backend/dist/uploads/profileImage/
    - mkdir -p /home/gitlab-runner/publicwebsite/backend/dist/tmp/
    - chmod 777 -R /home/gitlab-runner/publicwebsite/backend/dist/uploads/
    - chmod 777 -R /home/gitlab-runner/publicwebsite/backend/dist/tmp/
