master:
  stage: deploy
  only:
    - master
  tags:
    - nsur-runner-1
  script:
    - cd /home/gitlab-runner/publicwebsite/frontend
    - git fetch origin master
    - git reset --hard origin/master
    - git clean -n -f -d
    - git pull
    - npm i --force
    - npm run build
