master:
  stage: deploy
  only:
    - master
  tags:
    - nsur-runner-1
  script:
    - cd /home/gitlab-runner/publicwebsite/frontend
    - git fetch origin master
    - git reset --hard origin/master
    - git clean -f -d
    - git pull
    - npm i --force
    - npm run build
    - cd /home/gitlab-runner/publicwebsite/backend
    - npm i
    - npm run build
    - npm i -g pm2
    - pm2 delete "premierx-backend" || exit_code=$?
    - pm2 start premieRx.pm2.config.js --env production
